// configuration file for app icons

export const Icons = {
  home: 'ios-home',
  plan: 'ios-list',
  diary: 'ios-book',
  news: 'logo-twitter',
  settings: 'ios-settings',
  stats: 'ios-stats',
  report: 'ios-clipboard',
  warningSign: 'ios-warning',
  copingStrategy: 'ios-build',
  lifeWorthLiving: 'ios-body',
  distractions: 'ios-paper-plane',
  contacts: 'ios-call',
  environmentSafe: 'ios-checkmark-circle',
  media: 'ios-images',
  delete: 'ios-trash',
  message: 'ios-text',
  email: 'ios-mail',
  camera: 'ios-camera',
  skills: 'ios-star',
  feelings: 'ios-person',
  medication: 'ios-medkit',
  generalDiary: 'ios-document',
  closeModal: 'ios-close',
  calendar: 'ios-calendar',
  edit: 'ios-create',
  info: 'ios-information-circle',
  password: 'ios-lock',
  clock: 'ios-time',
  dividerArrow: 'ios-arrow-forward',
  dividerArrowBack: 'ios-arrow-back',
  insights: 'ios-bulb',
  charts: 'ios-trending-up',
  dbt: 'ios-hand',
  up: 'ios-arrow-dropup',
  down: 'ios-arrow-dropdown',
  whatsapp: 'logo-whatsapp',
  location: 'ios-navigate',
  add: 'ios-add-circle',
  compare: 'ios-git-compare',
  tick: 'ios-checkmark',
  print: 'ios-print',
  notifications: 'ios-notifications',
  helpers: 'ios-people',
};
